name: main
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'
      - name: Run Test1
        run: node fist/Test1.js
