name: workflow2
on:
  workflow_run:
    workflows: ["main"] 
    types:
      - completed

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "workflow2"
