name: workflow4
on:
  workflow_run:
    workflows: ["workflow3"] 
    types:
      - completed

jobs:
  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "workflow4"
